feat: add translations to update menu item request
This commit adds the IHasTranslationsDto interface and
MenuItemTranslationDto to the UpdateMenuItemRequest class.
This allows for the menu item to be updated with translations.
The change was necessary because of a
javax.net.ssl.SSLHandshakeException: Remote host terminated
the handshake error, which was caused by a missing
translation property.
```